[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Iris = "sirmallard/iris@2.4.1"
Maid = "nightcycle/maid@2.2^"
Result = "nightcycle/result@0^"
